[package]
name = "i18n-embed-impl"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
proc-macro2 = "1.0"
toml = "0.5"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
i18n-build = { path = "../../i18n-build" }

[dependencies.syn]
version = "1.0.17"
default-features = false
features = ["derive", "parsing", "printing", "extra-traits", "proc-macro"]
