[package]
name = "cargo-i18n"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"
description = "Cargo subcommand to extract and build localization resources"
keywords = ["cargo", "build", "i18n", "gettext", "locale"]
license = "MIT"
categories = ["development-tools::cargo-plugins", "localization", "internationalization", "development-tools::build-utils"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# TODO: make gettext an optional dependency

[dependencies]
anyhow = "1.0"
tr = { version = "0.1", default-features = false, features = ["gettext"] }
walkdir = "2"
clap = "2.33.0"
i18n-embed = { path = "./i18n-embed" }
cargo-i18n-lib = { path = "./cargo-i18n-lib" }