[package]
name = "i18n-embed"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"
repository = "https://github.com/kellpossible/cargo-i18n"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i18n-embed-impl = { path = "./i18n-embed-impl" }
unic-langid = "0.8"
locale_config = { version = "0.3", optional = true }
fluent-langneg = "0.12"
web-sys = { version = "0.3", features = ["Window", "Navigator", "console"], optional = true }
rust-embed = "5"
gettext = { version = "0.4", optional = true }
tr = { version = "0.1", default-features = false, optional = true }

[features]
default = ["gettext-system"]

gettext-system = ["tr", "tr/gettext", "gettext"]

desktop-requester = ["locale_config"]
web-sys-requester = ["web-sys"]
