[package]
name = "i18n-embed"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
rust-embed = "5"
quote = "1.0.3"
proc-macro2 = "1.0"

[dependencies.syn]
version = "1.0.17"
# default-features = false
# features = ["derive", "parsing", "printing", "extra-traits", "proc-macro"]
