[package]
name = "i18n-embed"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i18n-embed-impl = { path = "./i18n-embed-impl" }
locale_config = { version = "0.3", optional = true }
web-sys = { version = "0.3", features = ["Window", "Navigator"], optional = true }

[features]
default = ["desktop-support"]
desktop-support = ["locale_config"]
web-sys-support = ["web-sys"]
