[package]
authors = ["Luke Frisken <l.frisken@gmail.com>"]
categories = ["localization", "internationalization", "development-tools::build-utils", "wasm"]
description = "Derive macros for the traits defined in i18n-embed to conveniently embed localizations from cargo-i18n into your application binary at runtime"
edition = "2018"
exclude = ["i18n/", "i18n.toml"]
keywords = ["embed", "macro", "i18n", "gettext", "locale"]
license = "MIT"
name = "i18n-embed"
readme = "README.md"
repository = "https://github.com/kellpossible/cargo-i18n/tree/master/i18n-embed"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
i18n-embed-impl = { version = "0.1", path = "./i18n-embed-impl" }
unic-langid = "0.8"
locale_config = { version = "0.3", optional = true }
fluent-langneg = "0.12"
web-sys = { version = "0.3", features = ["Window", "Navigator"], optional = true }
rust-embed = "5"
gettext = { version = "0.4", optional = true }
tr = { version = "0.1", default-features = false, optional = true }
log = "0.4"

[dev-dependencies]
doc-comment = "0.3"

[features]
default = ["gettext-system"]

gettext-system = ["tr", "tr/gettext", "gettext"]

desktop-requester = ["locale_config"]
web-sys-requester = ["web-sys"]
